export const COMPONENT_KEYWORDS = {
    HomeComponent: [
      'international healthcare',
      'online doctor consultation',
      'online doctor appointment',
      'online doctor egypt',
      'medical care application',
      'free online doctor consultation',
      'doctor home visit',
      'all medical specialties',
      'home visits doctors',
      'medical news',
      'medical consulatant',
      'online medical care',
      'remote medical care',
      'best online medical advice',
      'free online medical advice',
      'salamtak group',
      'clinic visits',
      'clinic reservation',
      'doctor clinic',
      'doctor clinic near me',
      'private doctor clinic near me',
      'family doctor clinic near me',
      'nearest doctor clinic',
      'near me doctor clinic',
      'nearest doctor clinic to me',
      'online clinic reservation',
      'online reservation app',
      'online reservation',
      'online clinic',
      'سلامتك',
      'سلامتك جروب',
      'كشف طبى',
      'كشف اونلاين',
      'خدمات الطبية',
      'صحتك هدفنا',
      'استشاره طبيه',
      'موقع طبي',
      'تطبيقات استشارات طبية',
      'حجز دكتور زياره منزليه',
      'رعاية طبية',
      'افضل موقع استشارات طبية',
      'استشارة طبية أون لاين',
      'عيادات طبية',
      'طلب دكتور كشف منزلي',
      'طلب الكشف المنزلي في مصر',
      'حجز بالعيادة',
      'حجز طبيب',
      'احجز دكتور',
      'استشارة طبية مجانية',
      'حجز دكتور اونلاين'
  ],
    FindComponent: [
      'online doctor consultation',
      'online doctor appointment',
      'online doctor egypt',
      'medical care application',
      'doctor home visit',
      'all medical specialties',
      'home visits doctors',
      'salamtak group',
      'clinic visits',
      'clinic reservation',
      'doctor clinic near me',
      'private doctor clinic near me',
      'family doctor clinic near me',
      'nearest doctor clinic',
      'near me doctor clinic',
      'nearest doctor clinic to me',
      'online clinic reservation',
      'online reservation app',
      'in clinic booking',
      'online reservation',
      'استشاره طبيه',
      'استشارة طبية أون لاين',
      'حجز طبي',
      'حجز دكتور اونلاين',
      'عيادة النساء والتوليد',
      'عيادة جلدية',
      'عيادة تجميل',
      'عيادة عيون',
      'عيادة علاج طبيعي',
      'عيادة اطفال',
      'عيادة الباطنة',
      'عيادة عظام',
      'عيادة أسنان'
    ],
    SalamtakGate: [
      'medical advices',
      'online medical advice free',
      'best online medical advice',
      'free online medical advice',
      'medical advice',
      'medical information',
      'free medical advice',
      'online medical advice',
      'free online consultation',
      'online medical care',
      'free online medical care',
      'med info',
      'online medcare information',
      'true or false medical information',
      'salamtak consultation',
      'salamtak medical advice',
      'salamtak medical advice for free',
      'salamtak medical information',
      'salamtak medical information for free',
      'salamtak consultation for free',
      'salamtak consultations',
      'معلومات طبية',
      'معلومات طبية عامة',
      'معلومات طبية مفيدة للحياة اليومية',
      'نصائح طبية',
      'نصائح طبية عامة',
      'مقالات طبيه',
      'مقال طبي'
  ],
  ContactUs: [
  'تواصل معنا',
  'Contact us'
  ],
  defaultKeywords:[
    'Salamtak',
    'سلامتك'
  ]
  };
  
  